"""Independent MATLAB/Python comparisons using arrays exported by MATLAB.

These tests deliberately skip when the reference MAT file is absent.  They
never replace MATLAB data with values generated by Python.
"""

from __future__ import annotations

import json
import os
import unittest
from pathlib import Path

import numpy as np
from scipy.io import loadmat

from dhts_py import dht2, dhtmtx, dhtord, gauge, idht2, rdht


TESTS_DIR = Path(__file__).resolve().parent
DEFAULT_REFERENCE = TESTS_DIR / "matlab" / "references" / "dhts_matlab_reference.mat"
REFERENCE = Path(os.environ.get("DHTS_MATLAB_REFERENCE", DEFAULT_REFERENCE)).expanduser()
METRICS_PATH = TESTS_DIR / "resultados" / "matlab" / "metrics.json"


def error_metrics(actual: np.ndarray, reference: np.ndarray) -> dict[str, float | bool]:
    difference = np.asarray(actual, dtype=np.float64) - np.asarray(reference, dtype=np.float64)
    absolute = np.abs(difference)
    return {
        "max_abs_error": float(np.max(absolute)),
        "mean_abs_error": float(np.mean(absolute)),
        "mse": float(np.mean(difference**2)),
        "rmse": float(np.sqrt(np.mean(difference**2))),
        "allclose": bool(np.allclose(actual, reference, atol=5e-13, rtol=5e-13)),
    }


def reconstruction_metrics(actual: np.ndarray, reference: np.ndarray) -> dict[str, float | bool]:
    metrics = error_metrics(actual, reference)
    data_range = float(np.max(reference) - np.min(reference))
    mse = float(metrics["mse"])
    metrics["psnr_db"] = float("inf") if mse == 0 else float(20 * np.log10(data_range / np.sqrt(mse)))
    return metrics


class TestMatlabEquivalence(unittest.TestCase):
    reference_data = None
    metrics: dict[str, dict[str, float | bool]] = {}

    def setUp(self):
        if not REFERENCE.is_file():
            self.skipTest(
                "PENDING MATLAB REFERENCE: run tests/matlab/generate_matlab_references.m"
            )
        if self.__class__.reference_data is None:
            self.__class__.reference_data = loadmat(REFERENCE, squeeze_me=True)

    @classmethod
    def tearDownClass(cls):
        if cls.metrics:
            METRICS_PATH.parent.mkdir(parents=True, exist_ok=True)
            METRICS_PATH.write_text(json.dumps(cls.metrics, indent=2, sort_keys=True), encoding="utf-8")

    def compare(self, name: str, actual, reference, *, atol=5e-13, rtol=5e-13):
        actual = np.asarray(actual)
        reference = np.asarray(reference)
        self.assertEqual(actual.shape, reference.shape, name)
        metrics = error_metrics(actual, reference)
        self.__class__.metrics[name] = metrics
        print(f"{name}: {metrics}")
        np.testing.assert_allclose(actual, reference, atol=atol, rtol=rtol, err_msg=name)

    def test_01_dhtmtx(self):
        for N, D in ((3, 3), (4, 4), (8, 3), (8, 8)):
            H, G = dhtmtx(N, D, 1)
            suffix = f"N{N}_D{D}"
            self.compare(f"dhtmtx_H_{suffix}", H, self.reference_data[f"H_{suffix}"])
            self.compare(f"dhtmtx_G_{suffix}", G, self.reference_data[f"G_{suffix}"])

    def test_02_dhtord(self):
        actual = dhtord(8, 3, 2)
        self.compare("dhtord_N8_D3", actual, self.reference_data["ord_N8_D3"], atol=0, rtol=0)

    def test_03_constant_image(self):
        actual = dht2(self.reference_data["constant_input"], 8, 3, 1, "symm")
        self.compare("constant_coefficients", actual, self.reference_data["constant_coefficients"])

    def test_04_horizontal_ramp(self):
        actual = dht2(self.reference_data["ramp_horizontal_input"], 8, 3, 1, "symm")
        reference = self.reference_data["ramp_horizontal_coefficients"]
        self.compare("horizontal_L10", actual[..., 1], reference[..., 1])
        self.compare("horizontal_L01", actual[..., 2], reference[..., 2])

    def test_05_vertical_ramp(self):
        actual = dht2(self.reference_data["ramp_vertical_input"], 8, 3, 1, "symm")
        reference = self.reference_data["ramp_vertical_coefficients"]
        self.compare("vertical_L10", actual[..., 1], reference[..., 1])
        self.compare("vertical_L01", actual[..., 2], reference[..., 2])

    def test_06_house_dht(self):
        actual = dht2(self.reference_data["house_input"], 8, 3, 1, "symm")
        reference = self.reference_data["house_coefficients"]
        labels = ("L00", "L10", "L01", "L20", "L11", "L02", "L30", "L21", "L12", "L03")
        for channel, label in enumerate(labels):
            self.compare(f"house_{label}", actual[..., channel], reference[..., channel])

    def test_07_gauge_theta(self):
        cartesian = self.reference_data["house_coefficients"]
        actual = gauge(cartesian, 8, 3, 1)
        reference = np.asarray(self.reference_data["theta_gauge"])
        angular_error = np.angle(np.exp(1j * (actual - reference)))
        metrics = error_metrics(angular_error, np.zeros_like(angular_error))
        self.__class__.metrics["gauge_theta_wrapped_2pi"] = metrics
        print(f"gauge_theta_wrapped_2pi: {metrics}")
        np.testing.assert_allclose(angular_error, 0.0, atol=5e-13, rtol=0)

    def test_08_rdht(self):
        actual = rdht(
            self.reference_data["house_coefficients"],
            8,
            3,
            "fwd",
            self.reference_data["theta_gauge"],
        )
        self.compare("rdht_forward", actual, self.reference_data["rdht_forward"])

    def test_09_rdht_inverse(self):
        cartesian = self.reference_data["house_coefficients"]
        theta = self.reference_data["theta_gauge"]
        forward = rdht(cartesian, 8, 3, "fwd", theta)
        recovered = rdht(forward, 8, 3, "inv", theta)
        self.compare("rdht_python_roundtrip", recovered, cartesian)
        self.compare("rdht_inverse_matlab", recovered, self.reference_data["rdht_inverse"])

    def test_10_complete_and_truncated_reconstruction(self):
        image = self.reference_data["reconstruction_input"]
        complete_coefficients = dht2(image, 8, 16, 1, "full")
        truncated_coefficients = dht2(image, 8, 3, 1, "full")
        self.compare(
            "reconstruction_complete_coefficients",
            complete_coefficients,
            self.reference_data["reconstruction_complete_coefficients"],
        )
        self.compare(
            "reconstruction_truncated_coefficients",
            truncated_coefficients,
            self.reference_data["reconstruction_truncated_coefficients"],
        )
        complete = idht2(complete_coefficients, image.shape, 8, 16, 1, "full")
        truncated = idht2(truncated_coefficients, image.shape, 8, 3, 1, "full")
        self.compare("reconstruction_complete", complete, self.reference_data["reconstruction_complete"])
        self.compare("reconstruction_truncated", truncated, self.reference_data["reconstruction_truncated"])
        self.__class__.metrics["complete_vs_original"] = reconstruction_metrics(complete, image)
        self.__class__.metrics["truncated_vs_original"] = reconstruction_metrics(truncated, image)


if __name__ == "__main__":
    unittest.main()
